# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f49eeb20474a9fc3f71ba41839d72e1a0ffaf12ea6f67f5f71111c78a47401893382f1d3b63962020facca12587d4fe10bdc3a4c34b7d85ff8df72e71946ab

test:
  secret_key_base: d78738f2454faaf4a5e70492c6d591a860537009d6660f14a0da8ebca1bfbeb35c678068c2effcdb01918be589112d9600b7727b346e4c904fa5b77bae5b36e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
